### ISSUE TITLE
Normalize project infrastructure 

### ISSUE THREAD

**Issue by VladP97** [letov2110/siteproject#1]
Нужно добавить нормальный `requirements.txt`, только с необходимыми пакетами для проекта.
Выпилить папку `bulma`, так как стили подтягиваются из cdn, а не с локальных файлов. 
Добавить `.gitignore` файл, в котором указать игнорирование всех папок `__pycache__` и папки `lib`. Разобраться какие пути из папки media надо добавить в гитигнор, сейчас файлы загруженные пользователями на проект хранятся на гите (а это какой то пиздец). Также нужно разобраться нужна ли папка `bin` на гите.

При заливке этих этих правок, на сервере нужно будет снести папку `lib` на сервере, и вызывать freeze на `requirements.txt`, чтобы не засирать сервер змейками, тетрисами и прочими важными вещами.

**Comment by letov2110** [comment]
well done
